name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build e Push da Imagem Docker
      - name: Build and Push Docker Image
        run: |
          docker build -t aluiznt/efast:v1.0 .
          docker push aluiznt/efast:v1.0

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Conectar ao servidor remoto via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/u485559575/domains/efastmenu.com/public_html
            docker-compose down
            docker-compose pull
            docker-compose up -d --build
